# Generated by Django 4.1.1 on 2022-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treat',
            name='picture',
        ),
        migrations.AddField(
            model_name='treat',
            name='picture_link',
            field=models.URLField(default='no pciture has been linked yet'),
        ),
        migrations.AlterField(
            model_name='treat',
            name='recipe_link',
            field=models.URLField(default='no recipe has been linked yet'),
        ),
    ]
