# Generated by Django 4.1.1 on 2022-09-21 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0002_alter_treat_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
