# Generated by Django 4.1.1 on 2022-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0004_rename_updated_note_edited_remove_note_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='cover_img',
            field=models.ImageField(default='no image', upload_to='images/'),
        ),
    ]
