# Generated by Django 4.1.1 on 2022-09-21 18:54

import aws
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0005_alter_treat_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='cover_img',
            field=models.ImageField(default='no image', upload_to=aws.main),
        ),
    ]
