# Generated by Django 4.1.1 on 2022-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treats", "0007_alter_treat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treat",
            name="cover_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
