# Generated by Django 4.1.1 on 2022-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treats", "0008_alter_treat_cover_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treat",
            name="rating",
            field=models.CharField(
                choices=[
                    ("1", "⭐"),
                    ("2", "⭐⭐"),
                    ("3", "⭐⭐⭐"),
                    ("4", "⭐⭐⭐⭐"),
                    ("5", "⭐⭐⭐⭐⭐"),
                ],
                default="3",
                max_length=1,
            ),
        ),
    ]
