# Generated by Django 4.1.1 on 2022-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0009_alter_treat_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
