# Generated by Django 4.1.1 on 2022-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0011_remove_treat_treats_trea_rating_84ecf9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='recipe_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
