# Generated by Django 4.1.1 on 2022-09-28 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treats', '0013_alter_treat_recipe_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_coupon', models.CharField(max_length=50)),
                ('treat', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason_for_coupon_date', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField()),
                ('coupon_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created'], name='treats_coup_created_45212d_idx'),
        ),
    ]
