# Generated by Django 4.1.1 on 2022-09-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treats", "0015_coupon_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="reason_for_coupon",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="coupon_recipient",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="reason_for_coupon_date",
            new_name="target_date",
        ),
    ]
