# Generated by Django 4.1.1 on 2022-09-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_baker_user',
            field=models.BooleanField(default=False),
        ),
    ]
