# Generated by Django 4.1.1 on 2022-10-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0021_alter_treat_rating_alter_treat_recipe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='is_recipient_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treat',
            name='rating',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='treat',
            name='recipe_source',
            field=models.TextField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
