# Generated by Django 4.1.1 on 2022-10-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0022_treat_is_recipient_request_alter_treat_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treat',
            options={'ordering': ['-rating', 'created', 'is_recipient_request']},
        ),
        migrations.RemoveIndex(
            model_name='treat',
            name='treats_trea_rating_8e628d_idx',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('Not sent yet', 'Not Sent Yet'), ('Waiting for response', 'Waiting For Response'), ('Pending Approval', 'Pending Approval'), ('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Expired', 'Expired')], default='Not sent yet', max_length=20),
        ),
        migrations.AddIndex(
            model_name='treat',
            index=models.Index(fields=['rating'], name='treats_trea_rating_84ecf9_idx'),
        ),
        migrations.AddIndex(
            model_name='treat',
            index=models.Index(fields=['is_recipient_request'], name='treats_trea_is_reci_e34cbb_idx'),
        ),
    ]
