# Generated by Django 4.1.1 on 2022-10-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0026_alter_treat_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
