# Generated by Django 4.1.1 on 2022-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0027_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('Not sent yet', 'Not Sent Yet'), ('Waiting for response', 'Waiting For Response'), ('Pending Approval', 'Pending Approval'), ('To Do', 'To Do'), ('Past Due', 'Past Due'), ('Done', 'Done'), ('Expired', 'Expired')], default='Not sent yet', max_length=20),
        ),
    ]
